[package]
name = "snowbridge-runtime-common"
version = "0.1.1"
authors = [ "Snowfork <contact@snowfork.com>" ]
edition = "2021"

[dependencies]
log = { version = "0.4.20", default-features = false }

frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
xcm = { package = "staging-xcm", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
xcm-builder = { package = "staging-xcm-builder", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
xcm-executor = { package = "staging-xcm-executor", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

snowbridge-core = { path = "../../primitives/core", default-features = false }

[dev-dependencies]

[features]
default = [ "std" ]
std = [
    "frame-support/std",
    "frame-system/std",
    "sp-arithmetic/std",
    "snowbridge-core/std",
    "xcm-builder/std",
    "xcm-executor/std",
    "xcm/std",
]
runtime-benchmarks = [
    "snowbridge-core/runtime-benchmarks",
    "xcm-builder/runtime-benchmarks",
    "xcm-executor/runtime-benchmarks",
]
