[package]
name = "westend-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Westend emulated chain"
publish = false

[lints]
workspace = true

[dependencies]

# Substrate
sp-core = { path = "../../../../../../../substrate/primitives/core", default-features = false, version = "29.0.0" }
sp-runtime = { path = "../../../../../../../substrate/primitives/runtime", default-features = false, version = "32.0.0" }
sp-authority-discovery = { path = "../../../../../../../substrate/primitives/authority-discovery", default-features = false, version = "27.0.0" }
sp-consensus-babe = { path = "../../../../../../../substrate/primitives/consensus/babe", default-features = false, version = "0.33.0" }
beefy-primitives = { package = "sp-consensus-beefy", path = "../../../../../../../substrate/primitives/consensus/beefy", version = "14.0.0" }
grandpa = { package = "sc-consensus-grandpa", path = "../../../../../../../substrate/client/consensus/grandpa", default-features = false, version = "0.20.0" }
pallet-staking = { path = "../../../../../../../substrate/frame/staking", default-features = false, version = "29.0.2" }

# Polkadot
polkadot-primitives = { path = "../../../../../../../polkadot/primitives", default-features = false, version = "8.0.1" }
westend-runtime-constants = { path = "../../../../../../../polkadot/runtime/westend/constants", default-features = false, version = "8.0.0" }
westend-runtime = { version = "8.0.0", path = "../../../../../../../polkadot/runtime/westend" }
parachains-common = { version = "8.0.0", path = "../../../../../common" }
emulated-integration-tests-common = { path = "../../../common", default-features = false, version = "4.0.0" }
