[package]
name = "people-westend-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "People Westend emulated chain"
publish = false

[dependencies]

# Substrate
sp-core = { path = "../../../../../../../../substrate/primitives/core", default-features = false, version = "29.0.0" }
frame-support = { path = "../../../../../../../../substrate/frame/support", default-features = false, version = "29.0.2" }
parachains-common = { version = "8.0.0", path = "../../../../../../common" }
cumulus-primitives-core = { path = "../../../../../../../primitives/core", default-features = false, version = "0.8.0" }
emulated-integration-tests-common = { path = "../../../../common", default-features = false, version = "4.0.0" }
people-westend-runtime = { version = "0.2.0", path = "../../../../../../runtimes/people/people-westend" }
testnet-parachains-constants = { path = "../../../../../../runtimes/constants", features = ["westend"], version = "1.0.0" }
