[package]
name = "snowbridge-system-runtime-api"
version = "0.1.0"
edition = "2021"
authors = ["Snowfork <contact@snowfork.com>"]
repository = "https://github.com/Snowfork/snowbridge"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
xcm = { package = "staging-xcm", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
snowbridge-core = { path = "../../../primitives/core", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-core/std",
	"sp-api/std",
	"sp-std/std",
	"xcm/std",
	"snowbridge-core/std",
]
