[workspace]
resolver = "2"
members = [
	"pallets/ethereum-beacon-client",
	"pallets/inbound-queue",
	"pallets/outbound-queue",
	"pallets/outbound-queue/merkle-tree",
	"pallets/outbound-queue/runtime-api",
	"pallets/system",
	"pallets/system/runtime-api",
	"primitives/beacon",
	"primitives/core",
	"primitives/ethereum",
	"primitives/router",
	"runtime/rococo-common",
	"runtime/runtime-common",
	"runtime/tests",
]
