[package]
name = "snowbridge-rococo-common"
version = "0.0.1"
authors = [ "Snowfork <contact@snowfork.com>" ]
edition = "2021"

[dependencies]
log = { version = "0.4.20", default-features = false }

frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
xcm = { package = "staging-xcm", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

[dev-dependencies]

[features]
default = [ "std" ]
std = [
    "frame-support/std",
    "xcm/std",
]
runtime-benchmarks = []
