[package]
name = "polkadot-parachain-bin"
version = "6.0.1"
authors.workspace = true
build = "build.rs"
edition.workspace = true
description = "Runs a polkadot parachain node which could be a collator."
license = "Apache-2.0"

[lints]
workspace = true

[[bin]]
name = "polkadot-parachain"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.74"
clap = { version = "4.4.18", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0" }
futures = "0.3.28"
hex-literal = "0.4.1"
log = "0.4.20"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
rococo-parachain-runtime = { version = "0.7.0", path = "../parachains/runtimes/testing/rococo-parachain" }
shell-runtime = { version = "0.8.0", path = "../parachains/runtimes/starters/shell" }
glutton-westend-runtime = { version = "4.0.0", path = "../parachains/runtimes/glutton/glutton-westend" }
seedling-runtime = { version = "0.8.0", path = "../parachains/runtimes/starters/seedling" }
asset-hub-rococo-runtime = { version = "0.12.0", path = "../parachains/runtimes/assets/asset-hub-rococo" }
asset-hub-westend-runtime = { version = "0.16.0", path = "../parachains/runtimes/assets/asset-hub-westend" }
collectives-westend-runtime = { version = "4.0.0", path = "../parachains/runtimes/collectives/collectives-westend" }
contracts-rococo-runtime = { version = "0.9.0", path = "../parachains/runtimes/contracts/contracts-rococo" }
bridge-hub-rococo-runtime = { version = "0.6.0", path = "../parachains/runtimes/bridge-hubs/bridge-hub-rococo" }
coretime-rococo-runtime = { version = "0.2.0", path = "../parachains/runtimes/coretime/coretime-rococo" }
coretime-westend-runtime = { version = "0.2.0", path = "../parachains/runtimes/coretime/coretime-westend" }
bridge-hub-westend-runtime = { version = "0.3.0", path = "../parachains/runtimes/bridge-hubs/bridge-hub-westend" }
penpal-runtime = { version = "0.15.1", path = "../parachains/runtimes/testing/penpal" }
jsonrpsee = { version = "0.20.3", features = ["server"] }
people-rococo-runtime = { version = "0.2.0", path = "../parachains/runtimes/people/people-rococo" }
people-westend-runtime = { version = "0.2.0", path = "../parachains/runtimes/people/people-westend" }
parachains-common = { version = "8.0.0", path = "../parachains/common" }
testnet-parachains-constants = { path = "../parachains/runtimes/constants", default-features = false, features = ["rococo", "westend"], version = "1.0.0" }
frame-benchmarking = { version = "29.0.0", path = "../../substrate/frame/benchmarking" }
frame-benchmarking-cli = { version = "33.0.0", path = "../../substrate/utils/frame/benchmarking-cli" }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false, version = "32.0.0" }
sp-io = { version = "31.0.0", path = "../../substrate/primitives/io" }
sp-core = { version = "29.0.0", path = "../../substrate/primitives/core" }
sp-session = { version = "28.0.0", path = "../../substrate/primitives/session" }
frame-try-runtime = { path = "../../substrate/frame/try-runtime", optional = true, version = "0.35.0" }
sc-consensus = { version = "0.34.0", path = "../../substrate/client/consensus/common" }
sp-tracing = { version = "16.0.0", path = "../../substrate/primitives/tracing" }
frame-support = { version = "29.0.2", path = "../../substrate/frame/support" }
sc-cli = { version = "0.37.0", path = "../../substrate/client/cli" }
sc-client-api = { version = "29.0.0", path = "../../substrate/client/api" }
sc-executor = { version = "0.33.0", path = "../../substrate/client/executor" }
sc-service = { version = "0.36.0", path = "../../substrate/client/service" }
sc-telemetry = { version = "16.0.0", path = "../../substrate/client/telemetry" }
sc-transaction-pool = { version = "29.0.0", path = "../../substrate/client/transaction-pool" }
sp-transaction-pool = { version = "27.0.0", path = "../../substrate/primitives/transaction-pool" }
sc-network = { version = "0.35.0", path = "../../substrate/client/network" }
sc-network-sync = { version = "0.34.0", path = "../../substrate/client/network/sync" }
sc-basic-authorship = { version = "0.35.0", path = "../../substrate/client/basic-authorship" }
sp-timestamp = { version = "27.0.0", path = "../../substrate/primitives/timestamp" }
sp-blockchain = { version = "29.0.0", path = "../../substrate/primitives/blockchain" }
sp-genesis-builder = { path = "../../substrate/primitives/genesis-builder", default-features = false, version = "0.8.0" }
sp-block-builder = { version = "27.0.0", path = "../../substrate/primitives/block-builder" }
sp-keystore = { version = "0.35.0", path = "../../substrate/primitives/keystore" }
sc-chain-spec = { version = "28.0.0", path = "../../substrate/client/chain-spec" }
sc-rpc = { version = "30.0.0", path = "../../substrate/client/rpc" }
sp-version = { version = "30.0.0", path = "../../substrate/primitives/version" }
sc-tracing = { version = "29.0.0", path = "../../substrate/client/tracing" }
sp-offchain = { version = "27.0.0", path = "../../substrate/primitives/offchain" }
frame-system-rpc-runtime-api = { version = "27.0.0", path = "../../substrate/frame/system/rpc/runtime-api" }
pallet-transaction-payment = { version = "29.0.0", path = "../../substrate/frame/transaction-payment" }
pallet-transaction-payment-rpc-runtime-api = { version = "29.0.0", path = "../../substrate/frame/transaction-payment/rpc/runtime-api" }
sp-std = { version = "14.0.0", path = "../../substrate/primitives/std" }
sp-inherents = { version = "27.0.0", path = "../../substrate/primitives/inherents" }
sp-api = { version = "27.0.0", path = "../../substrate/primitives/api" }
sp-consensus-aura = { version = "0.33.0", path = "../../substrate/primitives/consensus/aura" }
sc-sysinfo = { version = "28.0.0", path = "../../substrate/client/sysinfo" }
substrate-prometheus-endpoint = { version = "0.17.0", path = "../../substrate/utils/prometheus" }
sc-transaction-pool-api = { version = "29.0.0", path = "../../substrate/client/transaction-pool/api" }
frame-rpc-system = { package = "substrate-frame-rpc-system", path = "../../substrate/utils/frame/rpc/system", version = "29.0.0" }
pallet-transaction-payment-rpc = { version = "31.0.0", path = "../../substrate/frame/transaction-payment/rpc" }
substrate-state-trie-migration-rpc = { version = "28.0.0", path = "../../substrate/utils/frame/rpc/state-trie-migration-rpc" }

# Polkadot
# Use rococo-native as this is currently the default "local" relay chain
polkadot-cli = { path = "../../polkadot/cli", features = ["rococo-native"], version = "8.0.0" }
polkadot-primitives = { version = "8.0.1", path = "../../polkadot/primitives" }
polkadot-service = { version = "8.0.0", path = "../../polkadot/node/service" }
xcm = { package = "staging-xcm", path = "../../polkadot/xcm", version = "8.0.1" }
cumulus-client-cli = { version = "0.8.0", path = "../client/cli" }
cumulus-client-collator = { version = "0.8.0", path = "../client/collator" }
cumulus-client-consensus-aura = { version = "0.8.0", path = "../client/consensus/aura" }
cumulus-client-consensus-relay-chain = { version = "0.8.0", path = "../client/consensus/relay-chain" }
cumulus-client-consensus-common = { version = "0.8.0", path = "../client/consensus/common" }
cumulus-client-consensus-proposer = { version = "0.8.0", path = "../client/consensus/proposer" }
cumulus-client-parachain-inherent = { version = "0.2.0", path = "../client/parachain-inherent" }
cumulus-client-service = { version = "0.8.0", path = "../client/service" }
cumulus-primitives-aura = { version = "0.8.0", path = "../primitives/aura" }
cumulus-primitives-core = { version = "0.8.0", path = "../primitives/core" }
cumulus-relay-chain-interface = { version = "0.8.0", path = "../client/relay-chain-interface" }
color-print = "0.3.4"

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0", path = "../../substrate/utils/build-script-utils" }

[dev-dependencies]
assert_cmd = "2.0"
nix = { version = "0.26.1", features = ["signal"] }
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = ["macros", "parking_lot", "time"] }
wait-timeout = "0.2"

[features]
default = []
runtime-benchmarks = [
	"asset-hub-rococo-runtime/runtime-benchmarks",
	"asset-hub-westend-runtime/runtime-benchmarks",
	"bridge-hub-rococo-runtime/runtime-benchmarks",
	"bridge-hub-westend-runtime/runtime-benchmarks",
	"collectives-westend-runtime/runtime-benchmarks",
	"contracts-rococo-runtime/runtime-benchmarks",
	"coretime-rococo-runtime/runtime-benchmarks",
	"coretime-westend-runtime/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"glutton-westend-runtime/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"penpal-runtime/runtime-benchmarks",
	"people-rococo-runtime/runtime-benchmarks",
	"people-westend-runtime/runtime-benchmarks",
	"polkadot-cli/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
	"rococo-parachain-runtime/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"asset-hub-rococo-runtime/try-runtime",
	"asset-hub-westend-runtime/try-runtime",
	"bridge-hub-rococo-runtime/try-runtime",
	"bridge-hub-westend-runtime/try-runtime",
	"collectives-westend-runtime/try-runtime",
	"contracts-rococo-runtime/try-runtime",
	"coretime-rococo-runtime/try-runtime",
	"coretime-westend-runtime/try-runtime",
	"frame-support/try-runtime",
	"frame-try-runtime/try-runtime",
	"glutton-westend-runtime/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"penpal-runtime/try-runtime",
	"people-rococo-runtime/try-runtime",
	"people-westend-runtime/try-runtime",
	"polkadot-cli/try-runtime",
	"polkadot-service/try-runtime",
	"shell-runtime/try-runtime",
	"sp-runtime/try-runtime",
]
fast-runtime = [
	"bridge-hub-rococo-runtime/fast-runtime",
]
