[package]
name = "asset-hub-rococo-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Asset Hub Rococo emulated chain"
publish = false

[lints]
workspace = true

[dependencies]

# Substrate
sp-core = { path = "../../../../../../../../substrate/primitives/core", default-features = false, version = "29.0.0" }
frame-support = { path = "../../../../../../../../substrate/frame/support", default-features = false, version = "29.0.2" }
parachains-common = { version = "8.0.0", path = "../../../../../../common" }
cumulus-primitives-core = { path = "../../../../../../../primitives/core", default-features = false, version = "0.8.0" }
emulated-integration-tests-common = { path = "../../../../common", default-features = false, version = "4.0.0" }
asset-hub-rococo-runtime = { version = "0.12.0", path = "../../../../../../runtimes/assets/asset-hub-rococo" }
rococo-emulated-chain = { version = "0.1.0", path = "../../../relays/rococo" }
testnet-parachains-constants = { path = "../../../../../../runtimes/constants", features = ["rococo"], version = "1.0.0" }
