[package]
name = "bridge-hub-westend-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Bridge Hub Westend emulated chain"
publish = false

[lints]
workspace = true

[dependencies]

# Substrate
sp-core = { path = "../../../../../../../../substrate/primitives/core", default-features = false, version = "29.0.0" }
frame-support = { path = "../../../../../../../../substrate/frame/support", default-features = false, version = "29.0.2" }
parachains-common = { version = "8.0.0", path = "../../../../../../common" }
emulated-integration-tests-common = { path = "../../../../common", default-features = false, version = "4.0.0" }
bridge-hub-westend-runtime = { version = "0.3.0", path = "../../../../../../runtimes/bridge-hubs/bridge-hub-westend" }
bridge-hub-common = { path = "../../../../../../runtimes/bridge-hubs/common", default-features = false, version = "0.1.0" }
testnet-parachains-constants = { path = "../../../../../../runtimes/constants", features = ["westend"], version = "1.0.0" }
