[package]
authors.workspace = true
edition.workspace = true
name = "cumulus-ping"
version = "0.8.0"
license = "Apache-2.0"
description = "Ping Pallet for Cumulus XCM/UMP testing."

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

sp-std = { path = "../../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, version = "32.0.0" }
frame-support = { path = "../../../../substrate/frame/support", default-features = false, version = "29.0.2" }
frame-system = { path = "../../../../substrate/frame/system", default-features = false, version = "29.0.0" }

xcm = { package = "staging-xcm", path = "../../../../polkadot/xcm", default-features = false, version = "8.0.1" }

cumulus-primitives-core = { path = "../../../primitives/core", default-features = false, version = "0.8.0" }
cumulus-pallet-xcm = { path = "../../../pallets/xcm", default-features = false, version = "0.8.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm/std",
]

try-runtime = [
	"cumulus-pallet-xcm/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
