[package]
name = "snowbridge-system-runtime-api"
description = "Snowbridge System Runtime API"
version = "0.1.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition.workspace = true
repository.workspace = true
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
sp-core = { path = "../../../../../../substrate/primitives/core", default-features = false, version = "29.0.0" }
sp-std = { path = "../../../../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-api = { path = "../../../../../../substrate/primitives/api", default-features = false, version = "27.0.0" }
xcm = { package = "staging-xcm", path = "../../../../../../polkadot/xcm", default-features = false, version = "8.0.1" }
snowbridge-core = { path = "../../../primitives/core", default-features = false, version = "0.1.1" }

[features]
default = ["std"]
std = [
	"codec/std",
	"snowbridge-core/std",
	"sp-api/std",
	"sp-core/std",
	"sp-std/std",
	"xcm/std",
]
