[package]
name = "snowbridge-outbound-queue"
description = "Snowbridge Outbound Queue"
version = "0.1.1"
edition = "2021"
authors = ["Snowfork <contact@snowfork.com>"]
repository = "https://github.com/Snowfork/snowbridge"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.188", features = ["derive", "alloc"], default-features = false }
codec = { version = "3.6.1", package = "parity-scale-codec", default-features = false, features = [ "derive" ] }
scale-info = { version = "2.9.0", default-features = false, features = [ "derive" ] }
hex-literal = { version = "0.4.1", optional = true }

frame-benchmarking = { path = "../../../../substrate/frame/benchmarking", default-features = false, optional = true}
frame-support = { path = "../../../../substrate/frame/support", default-features = false }
frame-system = { path = "../../../../substrate/frame/system", default-features = false }
sp-core = { path = "../../../../substrate/primitives/core", default-features = false }
sp-std = { path = "../../../../substrate/primitives/std", default-features = false }
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false }
sp-io = { path = "../../../../substrate/primitives/io", default-features = false }
sp-arithmetic = { path = "../../../../substrate/primitives/arithmetic", default-features = false }

bridge-hub-common = { path = "../../../../cumulus/parachains/runtimes/bridge-hubs/common", default-features = false }

snowbridge-core = { path = "../../primitives/core", features = ["serde"], default-features = false }
snowbridge-outbound-queue-merkle-tree = { path = "merkle-tree", default-features = false }
ethabi = { git = "https://github.com/Snowfork/ethabi-decode.git", package = "ethabi-decode", branch = "master", default-features = false }

xcm = { package = "staging-xcm", path = "../../../../polkadot/xcm", default-features = false }

[dev-dependencies]
pallet-message-queue = { path = "../../../../substrate/frame/message-queue", default-features = false }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
hex-literal = { version = "0.4.1" }

[features]
default = ["std"]
std = [
    "serde/std",
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-arithmetic/std",
    "sp-std/std",
    "sp-io/std",
    "snowbridge-core/std",
    "snowbridge-outbound-queue-merkle-tree/std",
    "ethabi/std",
    "xcm/std",
    "bridge-hub-common/std",
]
runtime-benchmarks = [
    "snowbridge-core/runtime-benchmarks",
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "hex-literal",
    "bridge-hub-common/runtime-benchmarks",
]
