[package]
name = "substrate-frame-cli"
version = "33.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "cli interface for FRAME"
documentation = "https://docs.rs/substrate-frame-cli"
readme = "README.md"

[lints]
workspace = true

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
frame-support = { version = "29.0.2", path = "../../../frame/support" }
frame-system = { version = "29.0.0", path = "../../../frame/system" }
sc-cli = { version = "0.37.0", path = "../../../client/cli" }
sp-core = { version = "29.0.0", path = "../../../primitives/core" }
sp-runtime = { version = "32.0.0", path = "../../../primitives/runtime" }

[features]
default = []
