[package]
name = "bridge-hub-common"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Bridge hub common utilities"
license = "Apache-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "29.0.2" }
sp-std = { path = "../../../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "29.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "32.0.0" }
cumulus-primitives-core = { path = "../../../../primitives/core", default-features = false, version = "0.8.0" }
xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "8.0.1" }
pallet-message-queue = { path = "../../../../../substrate/frame/message-queue", default-features = false, version = "32.0.0" }
snowbridge-core = { path = "../../../../../bridges/snowbridge/parachain/primitives/core", default-features = false, version = "0.1.1" }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"pallet-message-queue/std",
	"scale-info/std",
	"snowbridge-core/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm/std",
]

runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"snowbridge-core/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
